services:
  db:
    image: postgres:16
    container_name: realtime_chat_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: realtime_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: realtime_chat_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    name: realtime_chat_pgdata