server.port=8081
spring.application.name=realtime-chat-api

# ==========================================
# CONFIGURAÇÕES DE CONEXÃO COM O POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/realtime_chat
spring.datasource.username=admin
spring.datasource.password=1234

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true